# training_texts = [
#     "The weather is beautiful today.",
#     "I had a great time at the party last night.",
#     "The movie I watched was outstanding.",
#     "The restaurant served delicious food.",
#     "The customer service was excellent.",
#     "The book I read was captivating.",
#     "The product I bought exceeded my expectations.",
#     "The hotel I stayed at was luxurious.",
#     "The concert was an amazing experience.",
#     "The performance of the athlete was impressive.",
#     "The service provided by the company was top-notch.",
#     "The museum exhibit was informative and engaging.",
#     "The software is efficient and user-friendly.",
#     "The beach was clean and serene.",
#     "The staff at the store was friendly and helpful.",
#     "The airline provided a smooth and comfortable flight.",
#     "The car I rented was in great condition.",
#     "The online shopping experience was convenient and hassle-free.",
#     "The park was well-maintained and had beautiful scenery.",
#     "The customer support was responsive and resolved my issue.",
#     "The weather is awful today.",
#     "I had a terrible time at the party last night.",
#     "The movie I watched was disappointing.",
#     "The restaurant served tasteless food.",
#     "The customer service was rude and unhelpful.",
#     "The book I read was boring and poorly written.",
#     "The product I bought was of poor quality.",
#     "The hotel I stayed at was dirty and uncomfortable.",
#     "The concert was a disappointing experience.",
#     "The performance of the athlete was underwhelming.",
#     "The service provided by the company was subpar.",
#     "The museum exhibit was lackluster and uninformative.",
#     "The software is buggy and difficult to use.",
#     "The beach was crowded and dirty.",
#     "The staff at the store was unfriendly and unhelpful.",
#     "The airline provided a turbulent and uncomfortable flight.",
#     "The car I rented was in poor condition.",
#     "The online shopping experience was frustrating and time-consuming.",
#     "The park was unkempt and had no amenities.",
#     "The customer support was unresponsive and did not resolve my issue.",
#     "I am sad"
# ]

# training_labels = [
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "positive",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative",
#     "negative"
# ]


positive_responses = [
    "That's great to hear!",
    "I'm glad you enjoyed it.",
    "Wonderful!",
    "Excellent choice!",
    "Fantastic!",
    "That's amazing!",
    "I'm happy to hear that.",
    "That's a positive experience.",
    "Awesome!",
    "I'm thrilled for you.",
    "You made my day!",
    "You're doing great!",
    "Impressive!",
    "Well done!",
    "Keep up the good work!",
    "You're on the right track.",
    "Bravo!",
    "You nailed it!",
    "I'm proud of you!",
    "You've got this!",
    "You're making a difference.",
    "Outstanding job!",
    "I appreciate your effort.",
    "You're a star!",
    "You're an inspiration.",
    "That's a brilliant idea.",
    "I'm impressed by your skills.",
    "You're making progress.",
    "You're doing a fantastic job!",
    "You're shining bright.",
    "Great job!",
    "You're on fire!",
    "You're making a positive impact.",
    "Keep up the amazing work!",
    "You're a rockstar!",
    "You're bringing joy to others.",
    "You're a superstar!",
    "You're making a difference in people's lives.",
    "You're an asset to the team.",
    "You're an incredible person.",
    "That's outstanding!",
    "You're on a winning streak.",
    "You're an inspiration to others.",
    "You're a role model.",
    "You're doing phenomenal.",
    "You're a valuable team member.",
    "You're exceeding expectations.",
    "You're making great strides.",
    "You're a true professional.",
    "You're a champion!",
    "You're bringing positivity to the world.",
    "You're making a positive change.",
    "You're making a significant contribution.",
    "You're a true leader.",
    "You're extraordinary!",
    "You're an exceptional individual.",
    "You're highly skilled.",
    "You're a top performer.",
    "You're a force to be reckoned with.",
    "You're on top of your game.",
    "You're innovative and creative.",
    "You're making a difference in the community.",
    "You're an asset to the organization.",
    "You're a game-changer.",
    "You're a ray of sunshine.",
    "You're spreading positivity.",
    "You're an inspiration to others.",
    "You're a ray of hope.",
    "You're a breath of fresh air.",
    "You're a true gem.",
    "You're a bright star.",
    "You're an amazing individual.",
    "You're a positive role model.",
    "You're a beacon of light.",
    "You're a source of inspiration.",
    "You're making the world a better place.",
    "You're an exceptional talent.",
    "You're an invaluable asset.",
    "You're a ray of positivity.",
    "You're an incredible teammate.",
    "You're a true motivator.",
    "You're a ray of happiness.",
    "You're a true friend.",
    "You're an outstanding performer.",
    "You're a joy to work with.",
    "You're a true asset to the team.",
    "You're a wonderful person.",
    "You're a delight to be around.",
    "You're a true professional.",
    "You're a positive influence.",
    "You're a great teammate.",
    "You're a true talent.",
    "You're an extraordinary leader.",
    "You're a source of strength.",
    "You're a role model for others.",
    "You're making a lasting impact.",
    "You're an unstoppable force.",
    "You're an incredible asset.",
    "You're a valuable resource.",
    "You're a guiding light.",
    "You're a source of inspiration.",
    "You're an amazing team player.",
    "You're a true game-changer.",
    "You're a powerhouse of positivity.",
    "You're a superstar in the making.",
    "You're a catalyst for success.",
    "You're an exceptional mentor.",
    "You're an outstanding performer.",
    "You're a driving force.",
    "You're a source of encouragement.",
    "You're a true go-getter.",
    "You're a true visionary.",
    "You're a true asset to the organization.",
    "You're a beacon of inspiration.",
    "You're a true genius.",
    "You're a champion of change.",
    "You're a creative genius.",
    "You're a true talent.",
    "You're a dynamic individual.",
    "You're a remarkable person.",
    "You're a force of nature.",
    "You're a trailblazer.",
    "You're a master of your craft."
]

negative_responses = [
    "I'm sorry to hear that.",
    "That's disappointing.",
    "I understand how you feel.",
    "That's unfortunate.",
    "I apologize for the inconvenience.",
    "I'm here to help if you need assistance.",
    "Let's see if we can find a solution.",
    "I'll make a note of your feedback.",
    "I'll pass this on to the team.",
    "Thank you for bringing this to my attention.",
    "That's not good.",
    "I'm sorry it didn't meet your expectations.",
    "That's a letdown.",
    "I apologize for any inconvenience caused.",
    "I'll do my best to resolve this.",
    "Let me see what I can do.",
    "I'll look into this for you.",
    "I understand your frustration.",
    "I'll make sure this doesn't happen again.",
    "I'll take this as a learning opportunity.",
    "I'm here to assist you with any concerns.",
    "That's definitely a problem.",
    "I'll work on fixing this issue.",
    "I'm sorry if it caused any inconvenience.",
    "That's not what we strive for.",
    "I'll address this with the team.",
    "We appreciate your feedback.",
    "I'll pass this feedback along.",
    "I apologize for the inconvenience caused.",
    "That's unacceptable.",
    "I'll do everything I can to resolve this.",
    "I'll escalate this matter for you.",
    "I'm sorry for any trouble you've experienced.",
    "I'll investigate and get back to you.",
    "I understand your disappointment.",
    "I'll make sure to improve on this.",
    "I apologize for the inconvenience caused.",
    "I'll make a note of this for future reference.",
    "That's not up to our standards.",
    "I'll address this issue promptly.",
    "I'm sorry for any inconvenience caused.",
    "I'll take the necessary steps to fix this.",
    "I'll do my best to make it right.",
    "I apologize for the inconvenience you've faced.",
    "I'll work on resolving this for you.",
    "That's a valid concern.",
    "I'll pass your feedback to the relevant team.",
    "I'm sorry for the trouble you've encountered.",
    "I'll make sure to rectify this situation.",
    "I apologize for any frustration caused.",
    "That's definitely something we need to improve.",
    "I'll take your feedback into consideration.",
    "I'll make sure to learn from this experience.",
    "I apologize if we fell short of your expectations.",
    "I'll do my best to make things right.",
    "I understand your dissatisfaction.",
    "I'll make a note of your suggestion.",
    "I'm sorry if we let you down.",
    "I'll investigate this matter thoroughly.",
    "I apologize for the inconvenience you've faced.",
    "That's not the level of service we aim for.",
    "I'll personally see to it that this gets resolved.",
    "I'm sorry if we didn't meet your needs.",
    "I'll ensure this issue is resolved promptly.",
    "I understand your frustration and will work on fixing this.",
    "I apologize for any inconvenience caused.",
    "I'll make sure to address this issue.",
    "I'll do my best to make amends.",
    "I'm sorry for any inconvenience caused.",
    "I'll take your feedback into account.",
    "I'll make a note of your complaint.",
    "I apologize for any frustration you've experienced.",
    "I'll work on improving our services.",
    "I understand your disappointment and will take action.",
    "I'll make sure to learn from this mistake.",
    "I'm sorry if we let you down.",
    "I'll investigate this matter further for you.",
    "I apologize for any inconvenience you've faced.",
    "That's not what we aim for.",
    "I'll do my best to resolve this issue.",
    "I'm here to assist you in any way I can."
]

neutral_responses = [
    "I see.",
    "Interesting.",
    "Okay.",
    "That's good to know.",
    "I understand.",
    "Got it.",
    "Fair enough.",
    "That makes sense.",
    "I'm not sure.",
    "It depends.",
    "Maybe.",
    "I'm neutral on that.",
    "I have no opinion.",
    "I don't know.",
    "I'll consider it.",
    "I'm on the fence.",
    "I'll think about it.",
    "I'm undecided.",
    "That's neither good nor bad.",
    "I'm impartial.",
    "That's a neutral perspective.",
    "I'll reserve judgment.",
    "I have mixed feelings.",
    "I'm neither for nor against it.",
    "I'll remain neutral.",
    "I don't have a strong opinion.",
    "I don't have a preference.",
    "I don't lean one way or the other.",
    "I'm neutral on the matter.",
    "I'm on neutral ground.",
    "I'll stay neutral.",
    "I'm neither here nor there.",
    "I have no strong feelings about it.",
    "I'll stay neutral on that topic.",
    "That's a neutral statement.",
    "I don't have any bias.",
    "I'll stay on neutral territory.",
    "I'm impartial in this case.",
    "I'm not taking sides.",
    "I'm keeping an open mind.",
    "I'll stay neutral in my response.",
    "I'll give a neutral answer.",
    "That's a neutral viewpoint.",
    "I'll maintain a neutral stance.",
    "I'll stay on the fence for now.",
    "I don't have a particular inclination.",
    "I don't have a strong stance on this.",
    "I'll remain neutral in my opinion.",
    "I'm neutral in this matter.",
    "I don't have any strong emotions.",
    "I'll remain neutral in my assessment.",
    "I'll keep a neutral position.",
    "I'll withhold judgment.",
    "I'll stay neutral on this issue.",
    "I'm undecided at the moment.",
    "I'm not taking a side.",
    "I'll stay neutral in my response.",
    "I don't have any preferences.",
    "I'll maintain a neutral standpoint.",
    "I'll stay neutral in my analysis.",
    "I'm neutral in this argument.",
    "I'm not favoring either side.",
    "I don't have a strong inclination.",
    "I'll remain neutral on this subject.",
    "I don't have any strong opinions.",
    "I'll keep a neutral perspective.",
    "I'll provide a neutral view.",
    "I don't have any bias in this matter.",
    "I'll stay neutral in my viewpoint.",
    "I don't have any preferences.",
    "I'll keep an unbiased opinion.",
    "I'm impartial in this discussion.",
    "I'll stay neutral in my evaluation.",
    "I don't have a particular position.",
    "I'll remain neutral in my response.",
    "I'm not taking any sides.",
    "I'll provide a neutral assessment.",
    "I'm neutral in this debate.",
    "I don't have any strong feelings.",
    "I'll keep an open perspective.",
    "I'll stay neutral in my judgment.",
    "I don't have any preference.",
    "I'll remain neutral in my outlook.",
    "I'm not leaning one way or the other.",
    "I'll keep a neutral point of view.",
    "I'll stay neutral in my opinion.",
    "I don't have a strong viewpoint.",
    "I'll maintain a neutral position.",
    "I'll stay neutral in my conclusion.",
    "I'm impartial in this matter.",
    "I'm not taking any particular position.",
    "I'll stay neutral in my interpretation.",
    "I don't have any particular preference.",
    "I'll keep an unbiased perspective.",
    "I'll remain neutral in my understanding.",
    "I don't have a strong belief.",
    "I'll keep a neutral approach.",
    "I'll stay neutral in my analysis.",
    "I'm not favoring one side.",
    "I'll provide a neutral response.",
    "I'm neutral in this situation.",
    "I don't have any strong standpoint.",
    "I'll remain neutral in my assessment.",
    "I'll stay neutral in my evaluation.",
    "I don't have any strong standpoint.",
    "I'll remain neutral in my response.",
    "I'm not taking a particular side.",
    "I'll keep a neutral perspective.",
    "I'll stay neutral in my viewpoint."
]

